---
title: "Code for plotting Figure 1"
author: "Amy Tresenrider"
date: "2024-03-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


suppressPackageStartupMessages({ 
  library(tidyverse)
  library(ggplot2)
  library(tidyr)
  library(viridis)
  library(ggridges)
  library(purrr)
  library(monocle3)
  library(RColorBrewer)
  library(dplyr)
  library(dirmult)
  library(Seurat)
  library(cowplot)
  library(vioplot)
  library(ggrepel)
  library(gghighlight)
  library(data.table)
  
  # Pass TRUE if you want to see progress output on some of Monocle 3's operations
  DelayedArray:::set_verbose_block_processing(TRUE)
  # Passing a higher value will make some computations faster but use more memory. 
  # Adjust with caution!
  options(DelayedArray.block.size=1000e6)
  # Set a seed to make umap and other non-deterministic steps consistent
  set.seed(seed = 42)
  

})
```

```{r, load in the data}

cds = readRDS("GSM7670615_screen-glia_mg-derived_annotated_221117.RDS")
all_cds = readRDS("GSM7670615_screen-glia_all_hashed_cells_annotated_230406.RDS")
unfiltered_cds2 = readRDS("GSM7670615_screen-glia_cds_with_hash_data.RDS")

colors = read.csv("glia_colors.csv", header = F)

# function for plotting umaps by cell type
cell_type_plot = function(cds, name, cell_size, color_by) {
  
  gg1 = plot_cells(cds, color_cells_by = color_by, cell_size = cell_size,
                   label_cell_groups = F, x = 1, y = 2) +
    scale_color_manual(limits = colors$V1, values = colors$V3) +
    theme_void() + theme(legend.position = "none",
                         panel.border = element_rect(colour = "black", fill=NA, size=1),
                         panel.background = element_rect(fill = "white"))
  gg1
  save_plot(filename = paste0("Plots/", name, ".jpeg"), gg1, base_height = 3, base_width = 3)
  
}

```


### Main Figures
```{r, fig 2c}

cell_type_plot(cds, name = "f2c_reprogrammed_MG", cell_size = 0.2, color_by = "cell_type")

```

```{r, fig 2d}

cds$sample = as.factor(cds$sample)
gg1 = plot_cells(cds, color_cells_by = "sample", cell_size = 0.2,
                   label_cell_groups = F, x = 1, y = 2) +
    theme_void() + theme(legend.position = "none",
                         panel.border = element_rect(colour = "black", fill=NA, size=1),
                         panel.background = element_rect(fill = "white"))
save_plot(filename = paste0("Plots/f2d_reprog_sample.jpeg"), gg1, base_height = 3, base_width = 3)

```

```{r, fig 2e}

margin_spacer <- function(x) {
  # where x is the column in your dataset
  left_length <- nchar(levels(factor(x)))[1]
  if (left_length > 8) {
    return((left_length - 8) * 4)
  }
  else
    return(0)
}

# as cell_type as factor with specified order/levels
cds$cell_type = factor(cds$cell_type, levels = c("MG", "ProL_early", "ProL_late", "Transition", "NeuPre", "BP",
                                                 "ER_stressed", "Immune_reactive", "Undefined_neuron", "Unknown"))

dp2 = plot_genes_by_group(cds,
                    c("Ascl1", "Aqp4", "Rlbp1",  # mg
                      "Fn1", "Gfap", "Apoe", "Hes5", "Fosb", "Mpzl2", "Igfbp5", "Crip1", # different between early and late
                      "Gap43", "Snap25", "Dcx", # reprogramming
                      "Vsx2", "Cabp5", "Otx2", "Grik1", # most mature neuron
                      "Hspb1", "Trib3", # ER stressed
                      "Pik3ap1", "Mpeg1", # immune reactive
                      "Otx1", "Neto1", # undefined neuron
                      "Slc5a5", "Perp" # unkown
                      ), 
                    group_cells_by="cell_type",
                    ordering_type="none",
                    max.size=10,
                    norm_method = "log",
                    lower_threshold = 0.0001,
                    scale_max = 0.5,
                    axis_order = "marker_group") +
  scale_color_gradient(low = "#B2DCC1", high = "#26695E") +
  theme(axis.title = element_blank(),
        text = element_text(size = 16),
        plot.margin = margin(l = 0 + margin_spacer(cds$cell_type)),
        legend.position = "right")

save_plot(dp2, filename = "Plots/f2e_mg_cells_dot_plot_genes.jpeg", base_height = 4.2, base_width = 12)

```


```{r}
celltype_df
```

```{r, fig 2f}

colData(cds)$broad_cell_type = dplyr::recode(colData(cds)$cell_type,
                                                "ProL_early"="ProL",
                                                "ProL_late"="ProL",
                                                "Transition"="Transition",
                                                "NeuPre"="Neuronal",
                                                "BP"="Neuronal",
                                                "Unknown"="Unknown",
                                                "MG"="MG",
                                                "ER_stressed"="ER_stressed",
                                                "Immune_reactive"="Immune_reactive",
                                                "Undefined_neuron"="Undefined_neuron")

coldata_df = cds@colData %>% as.data.frame()
samples = unique(coldata_df$sample)
df.names = paste("celltype_df", samples, sep="")

for (s in samples) {
  sample_coldata_df = coldata_df %>% filter(sample == as.numeric(s))
  cds_summary = sample_coldata_df %>%
      group_by(top_oligo, broad_cell_type) %>%
      dplyr::summarize(cells = n())
  cell_counts_wide = tidyr::spread(cds_summary, broad_cell_type, cells, fill=0)
  top_oligo = as.character(cell_counts_wide %>% pull("top_oligo"))
  cell_counts_wide = as.matrix(cell_counts_wide[,2:ncol(cell_counts_wide)])
  row.names(cell_counts_wide) = top_oligo
  cell_counts_wide = t(cell_counts_wide) # cell types x top_oligo
  # can filter by total count in well
  cell_counts_wide = cell_counts_wide[,colSums(cell_counts_wide) > 40]
  total_cells = colSums(cell_counts_wide) %>% as.data.frame() %>% setNames("raw_total_cells") %>% rownames_to_column()
  sample_coldata_df = sample_coldata_df %>% 
      filter(top_oligo %in% colnames(cell_counts_wide))
  # account for size factors
  covariates_df = sample_coldata_df %>% 
      dplyr::select(top_oligo, drug_name, dose_uM, plate, drug_treatment) %>%
      distinct() %>% 
      as.data.frame %>%
      arrange(top_oligo)
  rownames(covariates_df) = covariates_df$top_oligo
  covariates_df$drug_name = as.character(covariates_df$drug_name)
  cell_count_cds = new_cell_data_set(expression_data = cell_counts_wide,
                                     cell_metadata = covariates_df[colnames(cell_counts_wide), ])
  cds_summary$size_factor = size_factors(cell_count_cds)[cds_summary$top_oligo]
  cds_summary = cds_summary %>% mutate(cells= round(cells/size_factor))
  celltype_df = cds_summary %>%
      ungroup() %>%
      group_by(top_oligo) %>%
      mutate(total_cells = sum(cells)) %>%
      ungroup() %>%
      mutate(broad_cell_type = as.factor(broad_cell_type)) %>%
      pivot_wider(names_from = broad_cell_type, values_from = cells, 
                  values_fill = list(cells = 0))
  # get unique cell types
  cell_types = coldata_df %>% pull(broad_cell_type) %>% unique()
  celltype_df = celltype_df %>% inner_join(covariates_df) %>% left_join(total_cells, by = c("top_oligo" = "rowname"))
  # assing name based on the sample
  assign(df.names[as.numeric(s)], celltype_df)
}

# threshold for mean number of cells per top_oligo for whether to test a cell type
mean_thresh = 1

# for df1
# pivot the celltype_df
all_summary1 = celltype_df1 %>%
    pivot_longer(cols = c("MG", "ProL", "Transition", "Neuronal",
                          "Unknown", "Undefined_neuron", "ER_stressed", "Immune_reactive"),
                 names_to = "broad_cell_type", values_to = "cells")
# Ascl1 only summary table
ascl1_df = all_summary1 %>%
    filter(drug_name == "Ascl1") %>%
    group_by(broad_cell_type) %>%
    summarize(ctrl_mean = round(mean(cells))) %>%
    ungroup() %>%
    distinct(broad_cell_type, ctrl_mean)

# perturbation summary table
fc_df1 = all_summary1 %>%
    filter(drug_name != "Ascl1") %>%
    group_by(drug_treatment, broad_cell_type) %>%
    summarize(mol_mean = round(mean(cells))) %>%
    left_join(ascl1_df, by = "broad_cell_type") %>%
    mutate(abund_log2fc = log2((mol_mean + 1)/(ctrl_mean+1)))

# for df2
# pivot the celltype_df
all_summary2 = celltype_df2 %>%
    pivot_longer(cols = c("MG", "ProL", "Transition", "Neuronal",
                          "Unknown", "Undefined_neuron", "ER_stressed", "Immune_reactive"),
                 names_to = "broad_cell_type", values_to = "cells")
# Ascl1 only summary table
ascl1_df = all_summary2 %>%
    filter(drug_name == "Ascl1") %>%
    group_by(broad_cell_type) %>%
    summarize(ctrl_mean = round(mean(cells))) %>%
    ungroup() %>%
    distinct(broad_cell_type, ctrl_mean)

# perturbation summary table
fc_df2 = all_summary2 %>%
    filter(drug_name != "Ascl1") %>%
    group_by(drug_treatment, broad_cell_type) %>%
    summarize(mol_mean = round(mean(cells))) %>%
    left_join(ascl1_df, by = "broad_cell_type") %>%
    mutate(abund_log2fc = log2((mol_mean + 1)/(ctrl_mean+1)))


fc_df1_wide = pivot_wider(fc_df1, id_cols = drug_treatment, names_from = broad_cell_type, values_from = abund_log2fc)
fc_df1_select = fc_df1_wide %>%
    dplyr::select(drug_treatment, Neuronal, ProL)
colnames(fc_df1_select) = paste(colnames(fc_df1_select),"log2fc",sep="_")
merge_df1 = merge(fc_df1_select, celltype_df1, by.x = "drug_treatment_log2fc", by.y = "drug_treatment")


fc_df2_wide = pivot_wider(fc_df2, id_cols = drug_treatment, names_from = broad_cell_type, values_from = abund_log2fc)
fc_df2_select = fc_df2_wide %>%
    dplyr::select(drug_treatment, Neuronal, ProL)
colnames(fc_df2_select) = paste(colnames(fc_df2_select),"log2fc",sep="_")
merge_df2 = merge(fc_df2_select, celltype_df2, by.x = "drug_treatment_log2fc", by.y = "drug_treatment")

merge_df1$experiment = 1
merge_df2$experiment = 2

# make the plots
text_size = 17
axis_size = 16

colors_fc = c("#DA6C7B")

merge_df1 = merge_df1 %>% arrange(Neuronal_log2fc) 
merge_df1$dose_uM[is.na(merge_df1$dose_uM)] = 0

ggplot(data = merge_df1, aes(x = reorder(drug_name, dplyr::desc(Neuronal_log2fc)), y = Neuronal_log2fc, 
                             size = log2(dose_uM + 1), color = as.factor(experiment))) + 
  scale_color_manual(values = colors_fc) +
  geom_point() +
  geom_point(shape = 1, color = "black") + 
  stat_summary(
    geom = "point",
    fun.y = "mean",
    col = "grey29",
    size = 7.5,
    shape = "-",
    fill = "black"
  ) +
  monocle3:::monocle_theme_opts() + 
  ylab("Neuron FC from Ascl1 only (log2)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none",
        axis.title.x = element_blank(),
        text = element_text(size = text_size),
        axis.title = element_text(size = axis_size),
        plot.margin = margin(5.5,5.5,5.5,35))
ggsave("Plots/f2f_new_fc_neurons_df1.jpeg", width = 8.5, height = 5.5)

merge_df2 = merge_df2 %>% arrange(Neuronal_log2fc) 
merge_df2$dose_uM[is.na(merge_df2$dose_uM)] = 0

ggplot(data = merge_df2, aes(x = reorder(drug_name, dplyr::desc(Neuronal_log2fc)), y = Neuronal_log2fc, 
                             size = log2(dose_uM + 1), color = as.factor(experiment))) + 
  scale_color_manual(values = colors_fc) +
  geom_point() +
  geom_point(shape = 1, color = "black") + 
  stat_summary(
    geom = "point",
    fun.y = "mean",
    col = "grey29",
    size = 10,
    shape = "-",
    fill = "black"
  ) +
  monocle3:::monocle_theme_opts() + 
  ylab("Neuron FC from Ascl1 only (log2)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none",
        axis.title.x = element_blank(),
        text = element_text(size = text_size),
        axis.title = element_text(size = axis_size))
ggsave("Plots/f2f_new_fc_neurons_df2.jpeg", width = 18, height = 5.5)

```
 
```{r, fig 2g}

color_count = c( "#FF8A30")

merge_df1 = merge_df1 %>% group_by(plate) %>% arrange(raw_total_cells, .by_group = T) 
merge_df1$drug_name = gsub("Metformin hydrochloride", "Metformin", merge_df1$drug_name)
ggplot(data = merge_df1, aes(x = reorder(drug_name, dplyr::desc(raw_total_cells)), y = raw_total_cells, 
                             size = log2(dose_uM + 1), color = as.factor(experiment))) + 
  scale_color_manual(values = color_count) +
  geom_point() +
  geom_point(shape = 1, color = "black") + 
  stat_summary(
    geom = "point",
    fun.y = "mean",
    col = "grey29",
    size = 10,
    shape = "-",
    fill = "black"
  ) +
  monocle3:::monocle_theme_opts() + 
  ylab("Total Cell Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none",
        axis.title.x = element_blank(),
        text = element_text(size = text_size),
        axis.title = element_text(size = axis_size),
        plot.margin = margin(5.5,5.5,5.5,35))
ggsave("Plots/f2g_new_cell_count_df1.jpeg", width = 9.25, height = 5.5)


merge_df2 = merge_df2 %>% group_by(plate) %>% arrange(raw_total_cells, .by_group = T) 
ggplot(data = merge_df2, aes(x = reorder(drug_name, dplyr::desc(raw_total_cells)), y = raw_total_cells, 
                             size = log2(dose_uM + 1), color = as.factor(experiment))) + 
  scale_color_manual(values = color_count) +
  geom_point() +
  geom_point(shape = 1, color = "black") + 
  stat_summary(
    geom = "point",
    fun.y = "mean",
    col = "grey29",
    size = 10,
    shape = "-",
    fill = "black"
  ) +
  monocle3:::monocle_theme_opts() + 
  ylab("Total Cell Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none",
        axis.title.x = element_blank(),
        text = element_text(size = text_size),
        axis.title = element_text(size = axis_size))
ggsave("Plots/f2g_new_cell_count_df2.jpeg", width = 18, height = 5.5)
 
```
 
```{r, fig 2h}

merge_longer = pivot_longer(merge_df1, cols = c("Neuronal_log2fc", "ProL_log2fc"), names_to = "log2fc")
merge_longer

drugs_of_interest = c("Metformin", "SB 431542")

for (i in drugs_of_interest) {
  drug_df = merge_longer[merge_longer$drug_name == i, ]
  zero_df = data.frame(drug_name = c(i, i) , dose_uM = c(0, 0), log2fc = c("Neuronal_log2fc", "ProL_log2fc"), value = c(0, 0))
  drug_df = rbind(drug_df, zero_df)
  
  ggplot(data=drug_df, aes(x=dose_uM, y=value, group=log2fc, color = log2fc)) +
    scale_color_manual(values = c("#D1495B", "#EDAE49")) +
    geom_line(linetype = "dashed") +
    geom_point(size = 5) +
    ylab("FC from Ascl1 only (log2)") + xlab("Dose (uM)") + ggtitle(i) +
    scale_x_continuous(trans = "log10") + 
    monocle3:::monocle_theme_opts() +
    theme(legend.position = "none",
          text = element_text(size = 18))
  ggsave(paste0("Plots/f2h", i, "dose_dependence.jpeg"), width = 4, height = 4)
}


merge_longer = pivot_longer(merge_df2, cols = c("Neuronal_log2fc", "ProL_log2fc"), names_to = "log2fc")
merge_longer

drugs_of_interest = c("DBZ", "RepSox", "DMH-1", "WH-4-023")

for (i in drugs_of_interest) {
  drug_df = merge_longer[merge_longer$drug_name == i, ]
  zero_df = data.frame(drug_name = c(i, i) , dose_uM = c(0, 0), log2fc = c("Neuronal_log2fc", "ProL_log2fc"), value = c(0, 0))
  drug_df = rbind(drug_df, zero_df)

  ggplot(data=drug_df, aes(x=dose_uM, y=value, group=log2fc, color = log2fc)) +
    scale_color_manual(values = c("#D1495B", "#EDAE49")) +
    geom_line(linetype = "dashed") +
    geom_point(size = 5) +
    scale_x_continuous(trans = "log10") + 
    ylab("FC from Ascl1 only (log2)") + xlab("Dose (uM)") + ggtitle(i) +
    monocle3:::monocle_theme_opts() +
    theme(legend.position = "none",
          text = element_text(size = 18))
  ggsave(paste0("Plots/f2h_", i, "dose_dependence.jpeg"), width = 4, height = 4)
}


```


### Supplemental Figures
```{r, fig s2a-c}

breaks_for_plot_x = c(1, 10, 100, 1000, 10000, 100000)
breaks_for_plot_y = c(1, 10, 30, 100, 300, 1000, 3000, 10000, 100000)

# RNA knee plot
p = unfiltered_cds2@colData %>% as.data.frame() %>%
  dplyr::select(cell, n.umi) %>%
  arrange(desc(n.umi)) %>%
  mutate(rank = dplyr::row_number()) %>%
  ggplot() +
  geom_line(aes(x = rank,
                y = n.umi)) +
  scale_x_log10(breaks = breaks_for_plot_x) +
  scale_y_log10(breaks = breaks_for_plot_y) +
  theme_classic() +
  geom_hline(yintercept = 500, 
             color = "red") +
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1)) + 
  xlab("Number of cells") +
  ylab("RNA UMIs")
umi_cds = unfiltered_cds2[, unfiltered_cds2@colData$n.umi > 500]

p4 = umi_cds@colData %>% as.data.frame() %>%
  dplyr::select(cell, perc_mitochondrial_umis) %>%
  ggplot() +
  geom_histogram(aes(perc_mitochondrial_umis), bins = 50) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 40)) + 
  scale_y_continuous(expand = c(0,0)) +
  monocle3:::monocle_theme_opts() +
  xlab("% Mitochondrial UMIs") +
  ylab("Cell Count") +
  geom_vline(xintercept = 15, col = "red")
mito_cds = umi_cds[, umi_cds@colData$perc_mitochondrial_umis < 15]

p2 = mito_cds@colData %>% as.data.frame() %>%
  dplyr::select(cell, top_to_second_best_ratio) %>%
  ggplot() +
  geom_histogram(aes(log2(top_to_second_best_ratio)), bins = 200) +
  scale_x_continuous(limits = c(0,12), expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0)) +
  monocle3:::monocle_theme_opts() +
  xlab("Top to second best ratio (log2)") + ylab("Cell Count") +
  geom_vline(xintercept = log2(5), col = "red")

pg = plot_grid(p, p4, p2, rel_widths = c(1, 1, 1), nrow = 1)
save_plot("Plots/S2a-c_hash_combined.jpeg", pg, base_height = 3, base_width = 10)

```
### need to add the data for this to the geo upload
```{r, fig s2d-f}

X
X
X
X
X
X
X
```

```{r, fig S2g}

coldata_df = all_cds@colData %>% as.data.frame()

to_count_df = coldata_df %>%
  group_by(sample, top_oligo) %>%
  summarize(n = n()) 

summ = to_count_df %>%
  summarize(n = n())

max = to_count_df %>%
  summarize(max = max(n))
min = to_count_df %>%
  ungroup() %>%
  summarise(mean = median(n)) 

count_violin = coldata_df %>%
  filter(top_oligo %in% to_count_df$top_oligo) %>%
  group_by(top_oligo, sample) %>%
  dplyr::count() %>%
  ggplot(aes(x = factor(sample), 
                        y = n, fill = factor(sample))) +
  geom_violin() +
  geom_dotplot(binaxis = "y",
               stackdir = "center",
               dotsize = 0.5) +
  geom_text(data = summ,
    aes(label = n, y = 50 + max$max),
    position = position_dodge(0.5),
    vjust = 0) +
  monocle3:::monocle_theme_opts() +
  scale_fill_manual(values = c("orange", "#008080")) +
  theme(axis.text.x = element_text(),
        axis.title.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 18)) +
  ylab("Cells per well") 
  
save_plot("Plots/S2g_violin_cells_per_well.jpeg", count_violin, base_height = 4, base_width = 4)

```

```{r, fig S2h}

numi_boxplot = all_cds@colData %>% as.data.frame() %>%
  group_by(sample) %>%
  ggplot(aes(x = factor(sample), 
                        y = n.umi, fill = factor(sample))) +
  geom_violin() +
  geom_boxplot(width = 0.1) +
  scale_y_continuous(trans = "log10") +
  monocle3:::monocle_theme_opts() +
  scale_fill_manual(values = c("orange", "#008080")) +
  theme(axis.title.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 18)) +
  ylab("UMIs per Cell") 

save_plot("Plots/S2h_bp_umis_per_cell.jpeg", numi_boxplot, base_height = 4, base_width = 4)

```

```{r, fig S2i}

all_cds = detect_genes(all_cds) 

nfeature_boxplot = all_cds@colData %>% as.data.frame() %>%
  group_by(treatment, top_oligo) %>%
  ggplot(aes(x = factor(sample), 
                        y = num_genes_expressed, fill = factor(sample))) +
  geom_violin() +
  geom_boxplot(width = 0.1) +
  scale_y_continuous(trans = "log10") +
  monocle3:::monocle_theme_opts() +
  scale_fill_manual(values = c("orange", "#008080")) +
  theme(axis.title.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 18)) +
  ylab("Features per Cell") 

save_plot("Plots/S2i_bp_features_per_organoid.jpeg", nfeature_boxplot, base_width = 4, base_height = 4)

```

```{r, fig S2j}

margin_spacer <- function(x) {
  # where x is the column in your dataset
  left_length <- nchar(levels(factor(x)))[1]
  if (left_length > 8) {
    return((left_length - 8) * 4)
  }
  else
    return(0)
}

# as cell_type as factor with specified order/levels
all_cds$cell_type = factor(all_cds$cell_type, levels = c("Bipolar", "Reprogramming", "Proliferating",
                                                         "Astrocyte-derived_neuron", "Astrocyte", "Microglia", "FibroL"))

dp1 = plot_genes_by_group(all_cds,
                    c("Ascl1", "Cabp5", "Otx2", # most mature neuron
                      "Aqp4", "Rlbp1",  # mg
                      "Vsx2", "Rax",  
                      "Mki67", "Top2a", # proliferating# marks cells that we want to carry forward
                      "Gap43", "Snap25", "Dcx", # reprogramming
                      "Pax2", "Gfap", # astrocytes
                      "P2ry12", "Spp1", # microglia
                      "Col4a1", "Lox", "Fn1" # unknown fibroblasts??
                      ), 
                    group_cells_by="cell_type",
                    ordering_type="none",
                    max.size=15,
                    norm_method = "log",
                    lower_threshold = 0.0001,
                    scale_max = 0.8,
                    axis_order = "marker_group") +
  scale_color_gradient(low = "#B2DCC1", high = "#26695E") +
  theme(axis.title = element_blank(),
        text = element_text(size = 20),
        plot.margin = margin(l = 0 + margin_spacer(cds$cell_type)),
        legend.position = "right")

save_plot(dp1, filename = "Plots/S2j_cells_dot_plot_genes.jpeg", base_height = 4.5, base_width = 12.5)

```

```{r, fig S2k}

cell_type_plot(all_cds, name = "S2k_all", cell_size = 0.1, color_by = "cell_type")

```

```{r, fig S2l}

all_cds$sample = as.factor(all_cds$sample)
gg1 = plot_cells(all_cds, color_cells_by = "sample", cell_size = 0.1,
                   label_cell_groups = F, x = 1, y = 2) +
    #scale_color_manual(values = colors$V2) +
    theme_void() + theme(legend.position = "none",
                         panel.border = element_rect(colour = "black", fill=NA, size=1),
                         panel.background = element_rect(fill = "white"))
gg1
save_plot(filename = paste0("Plots/S2l_all.jpeg"), gg1, base_height = 3, base_width = 3)

```

```{r, fig S2m}

# function
aggregated_expr_data <- function(cds, group_cells_by = "cell_type"){
  
  cell_group_df <- data.frame(row.names = row.names(colData(cds)), 
                              cell_id = row.names(colData(cds)))
  
  cell_group_df$cell_group <- colData(cds)[, group_cells_by]
  cell_group_df$cell_group <- as.character(cell_group_df$cell_group)
  cluster_binary_exprs = as.matrix(aggregate_gene_expression(cds, 
                                                             cell_group_df = cell_group_df, 
                                                             norm_method = "binary",
                                                             scale_agg_values=FALSE))
  
  cluster_fraction_expressing_table = tibble::rownames_to_column(as.data.frame(cluster_binary_exprs))
  cluster_fraction_expressing_table = tidyr::gather(cluster_fraction_expressing_table, 
                                                    "cell_group", "fraction_expressing", -rowname)
  cluster_mean_exprs = as.matrix(aggregate_gene_expression(cds, 
                                                           cell_group_df = cell_group_df, 
                                                           norm_method = "size_only",
                                                           scale_agg_values=FALSE))
  
  cluster_expr_table = tibble::rownames_to_column(as.data.frame(cluster_mean_exprs))
  cluster_expr_table = tidyr::gather(cluster_expr_table, "cell_group", 
                                     "mean_expression", -rowname)
  
  cluster_fraction_expressing_table$mean_expression = cluster_expr_table$mean_expression
  
  cluster_spec_mat = monocle3:::specificity_matrix(cluster_mean_exprs, cores = 4)
  cluster_spec_table = tibble::rownames_to_column(as.data.frame(cluster_spec_mat))
  cluster_spec_table = tidyr::gather(cluster_spec_table, "cell_group", 
                                     "specificity", -rowname)
  
  cluster_fraction_expressing_table$specificity = cluster_spec_table$specificity
  cluster_fraction_expressing_table = cluster_fraction_expressing_table %>% 
    dplyr::rename("gene_id" = rowname) %>% 
    dplyr::left_join(rowData(cds) %>% 
                       as.data.frame() %>%
                       dplyr::select("gene_id" = "id", gene_short_name), 
                     by = "gene_id") %>% 
    dplyr::select(cell_group, gene_id, gene_short_name, everything())
  
  return(cluster_fraction_expressing_table)
  
}

# application
cell_types = unique(cds@colData$cell_type)
specificity_table = aggregated_expr_data(cds = cds, group_cells_by = "cell_type")

for (type in cell_types) {
  filt_table = specificity_table %>% filter(fraction_expressing > 0.05, specificity > 0.3, cell_group == type)  %>% arrange(desc(specificity))
  write_csv(filt_table, paste0("Tables/specificity_genes_", type, ".csv"))
}

library(clusterProfiler)
library(org.Mm.eg.db)
library(data.table)
library(enrichplot)

### S2M
cluster = "ER_stressed"

cluster_table = fread(paste0("Tables/specificity_genes_", cluster, ".csv"))
gene <- cluster_table$gene_id
geneList = unique(specificity_table$gene_id)


ego <- enrichGO(gene          = gene,
                universe      = geneList,
                OrgDb         = org.Mm.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                keyType = "ENSEMBL",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
                readable      = TRUE)
p = barplot(ego, showCategory=10) + 
  scale_fill_viridis_c(option = "viridis", trans="log", label = function(x) sprintf("%.1e", x)) +
  theme(legend.position = "bottom",
        legend.key.width = unit(1, "cm"),
        legend.justification = c(1.15,0),
        axis.text.y = element_text(angle = 30, vjust = -0.1),
        text = element_text(size = 12))
save_plot(paste0("Plots/S2m_go_term_cluster_", cluster, ".jpeg"), p, base_height = 8, base_width = 4)

```

```{r, fig S2n}

### S2N
cluster = "Immune_reactive"

cluster_table = fread(paste0("Tables/specificity_genes_", cluster, ".csv"))
gene <- cluster_table$gene_id
geneList = unique(specificity_table$gene_id)


ego <- enrichGO(gene          = gene,
                universe      = geneList,
                OrgDb         = org.Mm.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                keyType = "ENSEMBL",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
                readable      = TRUE)
p = barplot(ego, showCategory=10) + 
  scale_fill_viridis_c(option = "viridis", trans="log", label = function(x) sprintf("%.1e", x)) +
  theme(legend.position = "bottom",
        legend.key.width = unit(1, "cm"),
        legend.justification = c(1.15,0),
        axis.text.y = element_text(angle = 30, vjust = -0.1),
        text = element_text(size = 12))
save_plot(paste0("Plots/S2n_go_term_cluster_", cluster, ".jpeg"), p, base_height = 8, base_width = 4)

```

```{r, fig S2o}

### S2O
cluster = "Undefined_neuron"

cluster_table = fread(paste0("Tables/specificity_genes_", cluster, ".csv"))
gene <- cluster_table$gene_id
geneList = unique(specificity_table$gene_id)


ego <- enrichGO(gene          = gene,
                universe      = geneList,
                OrgDb         = org.Mm.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                keyType = "ENSEMBL",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
                readable      = TRUE)
p = barplot(ego, showCategory=10) + 
  scale_fill_viridis_c(option = "viridis", trans="log", label = function(x) sprintf("%.1e", x)) +
  theme(legend.position = "bottom",
        legend.key.width = unit(1, "cm"),
        legend.justification = c(1.15,0),
        axis.text.y = element_text(angle = 30, vjust = -0.1),
        text = element_text(size = 12))
save_plot(paste0("Plots/S2o_go_term_cluster_", cluster, ".jpeg"), p, base_height = 8, base_width = 4)

```

```{r, fig S2p}

exp = 1

drug_treatments = unique(cds@colData %>% as.data.frame() %>%
                           filter(sample == exp) %>%
                           group_by(drug_treatment) %>%
                           dplyr::count() %>%
                           filter(n > 40)) %>%
  .$drug_treatment

treatment_list = c(drug_treatments)

hotspot_treat_df = cds[, cds@colData$drug_treatment %in% treatment_list]@colData %>% as.data.frame() %>% 
  filter(!grepl("Ascl1", drug_treatment))

cell_count_df = hotspot_treat_df %>% group_by(drug_treatment, sample, cell_type) %>% dplyr::count()

cell_count_wide_df = pivot_wider(cell_count_df, names_from = cell_type, values_from = n) %>% ungroup() %>% dplyr::select(-sample)

cell_count_wide_df = cell_count_wide_df %>% replace(is.na(.), 0)

cell_count_wide_df = column_to_rownames(cell_count_wide_df, var = "drug_treatment")

cell_count_wide_df = cell_count_wide_df[, c("MG", "ProL_early", "ProL_late", "Transition", "NeuPre", "BP",
                                            "ER_stressed", "Immune_reactive", "Undefined_neuron", "Unknown")]
 
p = pheatmap::pheatmap(cell_count_wide_df, scale = "row", fontsize_col = 12, 
                       treeheight_row = 0, treeheight_col = 0, cluster_cols = F, 
                       show_rownames = F, border_color = NA, color = viridis(100))

save_plot("Plots/S2p_hotspot_heatmap_all1.jpeg", p, base_height = 5, base_width = 4)




exp = 2

drug_treatments = unique(cds@colData %>% as.data.frame() %>%
                           filter(sample == exp) %>%
                           group_by(drug_treatment) %>%
                           dplyr::count() %>%
                           filter(n > 40)) %>%
  .$drug_treatment

treatment_list = c(drug_treatments)

hotspot_treat_df = cds[, cds@colData$drug_treatment %in% treatment_list]@colData %>% as.data.frame() %>% 
  filter(!grepl("Ascl1", drug_treatment))

cell_count_df = hotspot_treat_df %>% group_by(drug_treatment, sample, cell_type) %>% dplyr::count()

cell_count_wide_df = pivot_wider(cell_count_df, names_from = cell_type, values_from = n) %>% ungroup() %>% dplyr::select(-sample)

cell_count_wide_df = cell_count_wide_df %>% replace(is.na(.), 0)

cell_count_wide_df = column_to_rownames(cell_count_wide_df, var = "drug_treatment")

cell_count_wide_df = cell_count_wide_df[, c("MG", "ProL_early", "ProL_late", "Transition", "NeuPre", "BP",
                                            "ER_stressed", "Immune_reactive", "Undefined_neuron", "Unknown")]
 
p = pheatmap::pheatmap(cell_count_wide_df, scale = "row", fontsize_col = 12, 
                       treeheight_row = 0, treeheight_col = 0, cluster_cols = F, 
                       show_rownames = F, border_color = NA, color = viridis(100))

save_plot("Plots/S2p_hotspot_heatmap_all2.jpeg", p, base_height = 8, base_width = 4)

```

```{r, fig S2r} 

hash_df = cds@colData %>% as.data.frame() %>%
  group_by(drug_treatment, cell_type, sample) %>%
  dplyr::count()

# get total cells per oligo
total_cells  = hash_df %>% ungroup(cell_type) %>% dplyr::summarise(total_cells = sum(n)) %>% select(-sample)

merge_hash_df = left_join(hash_df, total_cells, by = "drug_treatment")
merge_hash_df = merge_hash_df %>% mutate(pct_ct = n/total_cells) %>% filter(total_cells > 20)

# get the remaining top oligos
include_oligos = c("TCS 2210_10uM", "ISX 9_10uM", "SAHA_1uM", "Alexidine dihydrochloride_1uM", 
                   "EC 19_10uM", "SW 033291_10uM", "CPI 203_10uM", "I-BET 151 dihydrochloride_10uM", 
                   "GW 788388_10uM", "RepSox_10uM", "DMH-1_1uM", "DBZ_0.1uM", "DBZ_1uM", 
                   "DMH-1_10uM", "WH-4-023_1uM","Ascl1_0uM", "RepSox_0.1uM", "CI 994_10uM", 
                   "SB 431542_10uM", "SB 431542_1uM", "GANT 61_10uM", "PD 98059_10uM")


# get cv for each cell type
cv_all = merge_hash_df %>% 
  ungroup(drug_treatment) %>%
  dplyr::summarise(stdev = sd(n), mean = mean(n)) %>%
  mutate(cv = stdev/mean)

treatments = unique(merge_hash_df$sample)

for (treat in treatments) {
  drug_order1 = c("Ascl1_0uM", "SB 431542_10uM", "SB 431542_1uM", "GANT 61_10uM", 
                  "PD 98059_10uM", "CI 994_10uM")
  drug_order2 = c("Ascl1_0uM", "DBZ_0.1uM", "DBZ_1uM", "DMH-1_1uM",  "DMH-1_10uM", 
                  "WH-4-023_1uM", "ISX 9_10uM", "SAHA_1uM", "TCS 2210_10uM", "Alexidine dihydrochloride_1uM", 
                  "EC 19_10uM", "SW 033291_10uM", "I-BET 151 dihydrochloride_10uM",
                  "CPI 203_10uM", "GW 788388_10uM", "RepSox_10uM")
  drug_order = list(drug_order1, drug_order2)
    
  # filter df and cv df for only a single treatment
  treat_df = merge_hash_df %>% filter(sample == treat, drug_treatment %in% drug_order[[as.numeric(treat)]])
  cv_order = c("MG", "ProL_early", "ProL_late", "Transition", "NeuPre", "BP",
                          "Unknown", "Undefined_neuron", "ER_stressed", "Immune_reactive")


  sizes = c(24, 20)
  gg = ggplot(treat_df, aes(fill=factor(cell_type, 
                                         levels = cv_order), 
                             y=n, 
                             x=factor(drug_treatment,
                                      levels = drug_order[[as.numeric(treat)]]))) +
    geom_bar(position="fill", stat="identity") +
    xlab("") + ylab("% Cell Type") +
    monocle3:::monocle_theme_opts() +
    scale_fill_discrete(name = "Cell Type") +
    scale_fill_manual(values = colors$V3, limits = colors$V1) +
    scale_y_continuous(expand = expansion(mult = c(0, 0))) +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1),
          text = element_text(size = sizes[treat])
          )
  
  gg 
  
  widths = c(6,12)
  save_plot(paste0("Plots/s1r_barplot_indiv1_", treat, ".jpeg"), gg, base_height = 6, base_width = widths[treat])
}
 
```




